### ISSUE TITLE
Question about usdm_drv memory

### ISSUE THREAD

**Issue by jhseodev** [intel/QAT_Engine#159]
I have a question about QAT memory allocation. (usdm_drv)

my nginx process smaps below. (anonymous memory approximately 1g)

When does anonymous memory allocated?
```
...
7f62a2a87000-7f62a2c87000 rwxs 1c5600000 00:05 11892                     /dev/usdm_drv
Size:               2048 kB
Rss:                   0 kB
Pss:                   0 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:            0 kB
Swap:                  0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
7f62a2c87000-7f62a4e87000 rwxp 00000000 00:00 0
Size:              34816 kB
Rss:               34464 kB
Pss:               34464 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:     34464 kB
Referenced:        34464 kB
Swap:                  0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
7f62a4e87000-7f62a5087000 rwxs 399a00000 00:05 11892                     /dev/usdm_drv
Size:               2048 kB
Rss:                   0 kB
Pss:                   0 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:            0 kB
Swap:                  0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
7f62a5087000-7f62a73a8000 rwxp 00000000 00:00 0
Size:              35972 kB
Rss:               35584 kB
Pss:               35584 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:     35584 kB
Referenced:        35584 kB
Swap:                  0 kB
KernelPageSize:        4 kB
...
```

**Comment by Yogaraj-Alamenda** [comment]
Hi @jhseodev  I don't have much information about anonymous memory, will check with USDM memory driver team and get back to you. Also, Could you please provide some more information about your use case like connection details . Also, whether do you use hugepages if so what page size do you use. ?

**Comment by jhseodev** [comment]
I checked that anonymous memory was allocated by openssl. I didn't use hugepage and hugepage file was not created.
I utilized strace and gdb to see openssl allocating anonymous memory via malloc call.
```
Breakpoint 1, 0x00007f8e8bce8770 in mmap64 () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f8e8bce8770 in mmap64 () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f8e8bc8034e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f8e8bc8203e in malloc () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f8e8c4947d0 in BUF_MEM_grow () from /opt/qat/QAT1.7/.openssl/lib/libcrypto.so.1.1
#4  0x00007f8e8c8dd91b in state_machine () from /opt/qat/QAT1.7/.openssl/lib/libssl.so.1.1
#5  0x00007f8e8c46a374 in async_start_func () from /opt/qat/QAT1.7/.openssl/lib/libcrypto.so.1.1
#6  0x00007f8e8bc4a2c0 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x0000000000000000 in ?? ()
(gdb) c
Continuing.

Breakpoint 1, 0x00007f8e8bce8770 in mmap64 () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f8e8bce8770 in mmap64 () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f8e8bc8034e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f8e8bc8203e in malloc () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f8e8c8b1a45 in ssl3_setup_write_buffer () from /opt/qat/QAT1.7/.openssl/lib/libssl.so.1.1
#4  0x00007f8e8c8b1b17 in ssl3_setup_buffers () from /opt/qat/QAT1.7/.openssl/lib/libssl.so.1.1
#5  0x00007f8e8c8dd70c in state_machine () from /opt/qat/QAT1.7/.openssl/lib/libssl.so.1.1
#6  0x00007f8e8c46a374 in async_start_func () from /opt/qat/QAT1.7/.openssl/lib/libcrypto.so.1.1
#7  0x00007f8e8bc4a2c0 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#8  0x0000000000000000 in ?? ()
(gdb) c
Continuing.
Breakpoint 1, 0x00007f8e8bce8770 in mmap64 () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f8e8bce8770 in mmap64 () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f8e8bc8034e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f8e8bc8203e in malloc () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f8e8c8b1925 in ssl3_setup_read_buffer () from /opt/qat/QAT1.7/.openssl/lib/libssl.so.1.1
#4  0x00007f8e8c8b162d in ssl3_read_bytes () from /opt/qat/QAT1.7/.openssl/lib/libssl.so.1.1
#5  0x00007f8e8c8e7c4e in tls_get_message_header () from /opt/qat/QAT1.7/.openssl/lib/libssl.so.1.1
#6  0x00007f8e8c8dd31d in state_machine () from /opt/qat/QAT1.7/.openssl/lib/libssl.so.1.1
#7  0x00007f8e8c46a374 in async_start_func () from /opt/qat/QAT1.7/.openssl/lib/libcrypto.so.1.1
#8  0x00007f8e8bc4a2c0 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#9  0x0000000000000000 in ?? ()
(gdb) c
```
I am still confused as to whether those anonymous memory is not being freed.

Thanks for posting the answer and sorry to report hastily. 

I'll close this issue.

Thank you!!
