### ISSUE TITLE
nginx -s reload can't shutdown "worker process"

### ISSUE THREAD

**Issue by lulin2008** [intel/QAT_Engine#201]
[](https://user-images.githubusercontent.com/4199809/160742929-10e1dc1f-ce53-425e-8a41-2438d2f442e5.png)QAT.L.4.15.0-00011
QAT_Engine-v0.6.10
openssl-1.1.1k

nginx.conf

ssl_engine {
use_engine qatengine;
default_algorithms ALL;
qat_engine {
qat_offload_mode async;
qat_notify_mode poll;
qat_poll_mode heuristic;
qat_sw_fallback on;
}
}

error:

image

debug:

pstack 363897
#0 0x00007fd4b2a796f0 in __read_nocancel () from /lib64/libpthread.so.0
https://github.com/intel/asynch_mode_nginx/issues/1 0x00007fd4b0aad8b5 in read (__nbytes=8, __buf=0x55c24bc9c7f8, __fd=) at /usr/include/bits/unistd.h:44
https://github.com/intel/asynch_mode_nginx/issues/2 qat_pause_job (job=, jobStatus=jobStatus@entry=2) at qat_events.c:278
https://github.com/intel/asynch_mode_nginx/issues/3 0x00007fd4b0ab465b in qat_chained_ciphers_do_cipher (ctx=0x55c24b51fc40, out=0x55c24b6b5638 "\233'Q\346\033\b\303F\367\323\323\301\377͎a\254\034\003u\033\066Ƥ:㐘泸7\351w}%\362\064\371J\216J\222\227\241\202\030\263\032\070+>\260\037\313\327\r\222\361\366\224\263\300\251Ș؀s\031D\344\221a\235ʝpt\321&\351{\254\304\373'j\241\346\374\370rIM\257ޖ\353@\242\021lO\217\375\222B\330\371\005I\354UWL\017U\274Ӹ\276Bq)l_nP\b\341\375ti|\b\b\313d\305\004\365?\177\020\324\251B.9\211r\231\322'\031\326h!\037\274\003ĳ\001^S\321\064ZlQ\022y/\256\213B\261\216\236\"\346\363\376\240\206KA\257\237\313\325\345/\033\231", <incomplete sequence \311>..., in=0x55c24b6b5638 "\233'Q\346\033\b\303F\367\323\323\301\377͎a\254\034\003u\033\066Ƥ:㐘泸7\351w}%\362\064\371J\216J\222\227\241\202\030\263\032\070+>\260\037\313\327\r\222\361\366\224\263\300\251Ș؀s\031D\344\221a\235ʝpt\321&\351{\254\304\373'j\241\346\374\370rIM\257ޖ\353@\242\021lO\217\375\222B\330\371\005I\354UWL\017U\274Ӹ\276Bq)l_nP\b\341\375ti|\b\b\313d\305\004\365?\177\020\324\251B.9\211r\231\322'\031\326h!\037\274\003ĳ\001^S\321\064ZlQ\022y/\256\213B\261\216\236\"\346\363\376\240\206KA\257\237\313\325\345/\033\231", <incomplete sequence \311>..., len=4208) at qat_hw_ciphers.c:1483
https://github.com/intel/asynch_mode_nginx/issues/4 0x00007fd4b1deaefc in tls1_enc () from /etc/nginx/.openssl/lib/libssl.so.1.1
https://github.com/intel/asynch_mode_nginx/pull/5 0x00007fd4b1deb9f6 in ssl3_get_record () from /etc/nginx/.openssl/lib/libssl.so.1.1
https://github.com/intel/asynch_mode_nginx/issues/6 0x00007fd4b1de8ec3 in ssl3_read_bytes () from /etc/nginx/.openssl/lib/libssl.so.1.1
https://github.com/intel/asynch_mode_nginx/issues/7 0x00007fd4b1df0b7a in ssl3_read () from /etc/nginx/.openssl/lib/libssl.so.1.1
https://github.com/intel/asynch_mode_nginx/issues/8 0x00007fd4b197e884 in async_start_func () from /etc/nginx/.openssl/lib/libcrypto.so.1.1
https://github.com/intel/asynch_mode_nginx/issues/9 0x00007fd4b155dd40 in ?? () from /lib64/libc.so.6
https://github.com/intel/asynch_mode_nginx/issues/10 0x0000000000000000 in ?? ()

pstack 363892
#0 0x00007fd4b2a796f0 in __read_nocancel () from /lib64/libpthread.so.0
https://github.com/intel/asynch_mode_nginx/issues/1 0x00007fd4b0aad8b5 in read (__nbytes=8, __buf=0x55c24c81dfc8, __fd=) at /usr/include/bits/unistd.h:44
https://github.com/intel/asynch_mode_nginx/issues/2 qat_pause_job (job=, jobStatus=jobStatus@entry=2) at qat_events.c:278
https://github.com/intel/asynch_mode_nginx/issues/3 0x00007fd4b0ab465b in qat_chained_ciphers_do_cipher (ctx=0x55c24bf744d0, out=0x55c24b5bdfc8 "$\244D\255\336\066\037\002\346Ƹ/ɂS\032V\254\060\251ش#w\372\362\367\061\241\025ʆ\035W\266\225)m@\331\n/:\020=\237雁a\n\340C!\354\270\367|\232\236\031\304<K\254.\267\246\376v|\026\310aa\005\202Kզ!m\265\344\262F\372\204\244\021=\263^\326.a\210\tD"\254\066M$t?BoT]\254n\356*\216\372\231\247\066\237]jj\304T\235\026q%tmC!\301Ɩ\267\340K?1\302\200\361^q", in=0x55c24b5bdfc8 "$\244D\255\336\066\037\002\346Ƹ/ɂS\032V\254\060\251ش#w\372\362\367\061\241\025ʆ\035W\266\225)m@\331\n/:\020=\237雁a\n\340C!\354\270\367|\232\236\031\304<K\254.\267\246\376v|\026\310aa\005\202Kզ!m\265\344\262F\372\204\244\021=\263^\326.a\210\tD"\254\066M$t?BoT]\254n\356*\216\372\231\247\066\237]jj\304T\235\026q%tmC!\301Ɩ\267\340K?1\302\200\361^q", len=3088) at qat_hw_ciphers.c:1483
https://github.com/intel/asynch_mode_nginx/issues/4 0x00007fd4b1deaefc in tls1_enc () from /etc/nginx/.openssl/lib/libssl.so.1.1
https://github.com/intel/asynch_mode_nginx/pull/5 0x00007fd4b1deb9f6 in ssl3_get_record () from /etc/nginx/.openssl/lib/libssl.so.1.1
https://github.com/intel/asynch_mode_nginx/issues/6 0x00007fd4b1de8ec3 in ssl3_read_bytes () from /etc/nginx/.openssl/lib/libssl.so.1.1
https://github.com/intel/asynch_mode_nginx/issues/7 0x00007fd4b1df0b7a in ssl3_read () from /etc/nginx/.openssl/lib/libssl.so.1.1
https://github.com/intel/asynch_mode_nginx/issues/8 0x00007fd4b197e884 in async_start_func () from /etc/nginx/.openssl/lib/libcrypto.so.1.1
https://github.com/intel/asynch_mode_nginx/issues/9 0x00007fd4b155dd40 in ?? () from /lib64/libc.so.6
https://github.com/intel/asynch_mode_nginx/issues/10 0x0000000000000000 in ?? ()

help me!!!

**Comment by Yogaraj-Alamenda** [comment]
Hi it seems to me there is some inflight requests. We will try reproducing this bug and let you know. Can you please share Nginx cipher command used and number of process configured in nginx ?
